import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

// `scripts/setup-env.js` liczy wszystko względem swojego `__dirname/..`, więc
// uruchamiamy jego kopię w katalogu tymczasowym. Skrypt zależy wyłącznie od
// modułów wbudowanych (fs, path, net, crypto), kopia jest więc kompletna.
const SOURCE = path.join(__dirname, '..', '..', 'scripts', 'setup-env.js');

let root: string;

function runSetupEnv(): string {
  return execFileSync(process.execPath, [path.join(root, 'scripts', 'setup-env.js')], {
    cwd: root,
    encoding: 'utf8',
  });
}

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'setup-env-'));
  fs.mkdirSync(path.join(root, 'scripts'));
  fs.copyFileSync(SOURCE, path.join(root, 'scripts', 'setup-env.js'));
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

describe('ensureEnvironment: czysty checkout', () => {
  // Brakujące katalogi bind-mountu tworzy demon Dockera jako root i takie
  // zostają na hoście. `data/home` to HOME kontenera (`~/.claude.json`),
  // więc musi powstać wcześniej i pod użytkownikiem — tak jak `data/`
  // i `data/projects`, które ten skrypt tworzy od zawsze.
  it('tworzy data/home obok data i data/projects', () => {
    runSetupEnv();

    expect(fs.existsSync(path.join(root, 'data'))).toBe(true);
    expect(fs.existsSync(path.join(root, 'data', 'projects'))).toBe(true);
    expect(fs.existsSync(path.join(root, 'data', 'home'))).toBe(true);
  });
});

describe('ensureEnvironment: zastane .env.local', () => {
  // Skrypt przestał pisać `.env.local`, ale istniejąca instalacja trzyma
  // zamrożoną kopię — a `.env.local` wygrywa z `.env` u własnego loadera Nexta
  // (`next build`/`next start`) i w `scripts/migrate-drop-legacy.js`
  // (`override: true`). Zamrożone `PREVIEW_PORT_END=3999` biłoby więc wartość
  // policzoną tutaj.
  it('usuwa z .env.local klucze, które teraz liczy .env', () => {
    fs.writeFileSync(
      path.join(root, '.env.local'),
      '# Auto-generated by scripts/setup-env.js\nPREVIEW_PORT_END=3999\nPORT=3000\nMY_OWN_KEY=zostaje\n'
    );

    runSetupEnv();

    const contents = fs.readFileSync(path.join(root, '.env.local'), 'utf8');
    expect(contents).not.toMatch(/^PREVIEW_PORT_END=/m);
    expect(contents).not.toMatch(/^PORT=/m);
    expect(contents).toMatch(/^MY_OWN_KEY=zostaje$/m);
  });

  it('kasuje .env.local, gdy nie zostaje w nim nic poza komentarzami', () => {
    fs.writeFileSync(
      path.join(root, '.env.local'),
      '# Auto-generated by scripts/setup-env.js\nPORT=3000\nWEB_PORT=3000\nNEXT_PUBLIC_APP_URL=http://localhost:3000\nPREVIEW_PORT_START=3100\nPREVIEW_PORT_END=3999\n'
    );

    runSetupEnv();

    expect(fs.existsSync(path.join(root, '.env.local'))).toBe(false);
  });

  it('nie rusza .env.local bez zarządzanych kluczy', () => {
    const own = 'MY_OWN_KEY=zostaje\n';
    fs.writeFileSync(path.join(root, '.env.local'), own);

    runSetupEnv();

    expect(fs.readFileSync(path.join(root, '.env.local'), 'utf8')).toBe(own);
  });
});
